name: Change "Hello" workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 * * * *' # Runs every hour, on the hour
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly
jobs:
  hello-change:
    name: Update this repo's README with greeting in different languages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: #actions
        with:
          feed_list: "" #link